header:
  version: 14

distro: rz-bsp-plus

build_system: openembedded

repos:
  meta-renesas:
    layers:
      meta-rz-distro:
      meta-rz-bsp:
  poky:
    url: "https://git.yoctoproject.org/git/poky"
    # scarthgap-5.0.8
    commit: dc4827b3660bc1a03a2bc3b0672615b50e9137ff
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
  meta-arm:
    url: https://git.yoctoproject.org/meta-arm
    # yocto-5.0.1
    commit: 950a4afce46a359def2958bd9ae33fc08ff9bb0d
    layers:
      meta-arm-toolchain:
      meta-arm:
  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    # scarthgap HEAD
    commit: 67ad83dd7c2485dae0c90eac345007af6195b84d
    layers:
      meta-oe:

bblayers_conf_header:
  standard: |
    POKY_BBLAYERS_CONF_VERSION = "2"

local_conf_header:
  standard: |
    CONF_VERSION = "2"
    BB_DISKMON_DIRS ?= " \
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K \
    "

    # Extra image configuration defaults
    EXTRA_IMAGE_FEATURES = "debug-tweaks tools-profile tools-testapps"

    # Remove dnf package which causes high CPU workload
    PACKAGE_INSTALL:remove = " dnf "

    # Additional image features
    USER_CLASSES ?= "buildstats"

    # Kernel version 6.12 for bsp plus
    PREFERRED_VERSION_linux-renesas = "6.12%"
